// Instacart Developer Platform API integration
// Docs: https://docs.instacart.com/developer_platform_api/
// Endpoint: POST /idp/v1/products/recipe

const INSTACART_API_BASE = "https://connect.instacart.com";

// Human-readable search names for each ingredient key.
// These are what Instacart uses to find the right product.
const SEARCH_NAMES = {
  salmon:          "salmon fillet",
  sardines:        "sardines canned in water",
  chickenThighs:   "chicken thighs boneless skinless",
  groundTurkey:    "ground turkey",
  grassBeef:       "grass fed ground beef",
  eggs:            "large eggs",
  shrimp:          "large shrimp peeled deveined frozen",
  lentils:         "green lentils dry",
  spinach:         "baby spinach",
  broccoli:        "broccoli florets",
  zucchini:        "zucchini squash",
  asparagus:       "fresh asparagus",
  cabbage:         "green cabbage",
  peppers:         "bell peppers",
  mushrooms:       "cremini mushrooms",
  greenBeans:      "fresh green beans",
  sweetPotato:     "sweet potatoes",
  cauliflowerRice: "cauliflower rice",
  tomatoes:        "roma tomatoes",
  onions:          "yellow onion",
  garlic:          "garlic bulb",
  oliveOil:        "extra virgin olive oil",
  avocado:         "hass avocado",
  walnuts:         "raw walnuts",
  chia:            "chia seeds",
  turmeric:        "ground turmeric",
  ginger:          "fresh ginger root",
  tamari:          "gluten free tamari soy sauce",
  coconutMilk:     "coconut milk full fat",
  tahini:          "tahini sesame paste"
};

// Friendly display labels shown to the customer on the Instacart recipe page
const DISPLAY_LABELS = {
  salmon: "Salmon", sardines: "Sardines (canned)", chickenThighs: "Chicken thighs",
  groundTurkey: "Ground turkey", grassBeef: "Grass-fed beef", eggs: "Eggs",
  shrimp: "Shrimp", lentils: "Lentils", spinach: "Baby spinach", broccoli: "Broccoli",
  zucchini: "Zucchini", asparagus: "Asparagus", cabbage: "Cabbage",
  peppers: "Bell peppers", mushrooms: "Mushrooms", greenBeans: "Green beans",
  sweetPotato: "Sweet potatoes", cauliflowerRice: "Cauliflower rice",
  tomatoes: "Tomatoes", onions: "Onions", garlic: "Garlic",
  oliveOil: "Olive oil (EVOO)", avocado: "Avocado", walnuts: "Walnuts",
  chia: "Chia seeds", turmeric: "Turmeric", ginger: "Fresh ginger",
  tamari: "Tamari (GF soy sauce)", coconutMilk: "Coconut milk", tahini: "Tahini"
};

// Instacart accepted units — map our internal units to their expected format
function normaliseUnit(unit) {
  const map = { lb: "lb", cup: "cup", each: "each", can: "can",
    tbsp: "tablespoon", tsp: "teaspoon", clove: "clove", oz: "oz", bunch: "bunch" };
  return map[unit] ?? unit;
}

function buildIngredients(groceryList) {
  return groceryList
    .filter((g) => SEARCH_NAMES[g.ingredientKey])
    .map((g) => {
      const displayLabel = DISPLAY_LABELS[g.ingredientKey] ?? g.ingredientKey;
      const roundedQty = Math.round(g.amount * 100) / 100;
      return {
        name: SEARCH_NAMES[g.ingredientKey],
        display_text: `${roundedQty} ${g.unit} — ${displayLabel}`,
        measurements: [
          { quantity: roundedQty, unit: normaliseUnit(g.unit) }
        ]
      };
    });
}

export async function POST(request) {
  const { groceryList, weekStart, appUrl } = await request.json();

  const apiKey = process.env.INSTACART_API_KEY;

  if (!apiKey) {
    return Response.json(
      { error: "INSTACART_API_KEY not configured — add it to .env.local and Vercel env vars" },
      { status: 503 }
    );
  }

  const ingredients = buildIngredients(groceryList);

  if (!ingredients.length) {
    return Response.json({ error: "No mappable ingredients found in grocery list" }, { status: 400 });
  }

  const payload = {
    title: `Meal Ops — Anti-Inflammatory Week of ${weekStart}`,
    image_url: `${appUrl ?? "https://meal-ops.vercel.app"}/og-image.png`,
    link_type: "recipe",
    instructions: [
      "This grocery list was generated by Meal Ops — your AI-powered anti-inflammatory meal planner.",
      "Select the items you need, mark anything you already have at home, then add to cart.",
      "Items support HEB, Whole Foods, and 85,000+ other retailers on Instacart."
    ],
    ingredients,
    landing_page_configuration: {
      partner_linkback_url: appUrl ?? "https://meal-ops.vercel.app",
      enable_pantry_items: true
    }
  };

  try {
    const res = await fetch(`${INSTACART_API_BASE}/idp/v1/products/recipe`, {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${apiKey}`,
        "Content-Type": "application/json",
        "Accept": "application/json"
      },
      body: JSON.stringify(payload)
    });

    if (!res.ok) {
      const errText = await res.text();
      console.error("Instacart API error:", res.status, errText);
      return Response.json({ error: `Instacart API error ${res.status}: ${errText}` }, { status: res.status });
    }

    const data = await res.json();
    return Response.json({ url: data.products_link_url, itemCount: ingredients.length });
  } catch (err) {
    console.error("Instacart fetch failed:", err);
    return Response.json({ error: err.message }, { status: 500 });
  }
}
